/* Generated by Yosys 0.65+51 (git sha1 5c6de0446-dirty, aarch64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) */

module foliation_fpu_mapped(_037_, _038_, _039_, _040_, _041_, _042_, _043_, _044_, _045_, _046_, _047_, _048_, _049_, _050_, _051_, _052_, _053_, _054_, _055_, _056_, _057_
, _058_, _059_, _060_, _061_, _062_, _063_, _064_, _065_, _066_, _067_, _068_, _069_, _070_, _071_, _072_, _073_, _074_, _075_, _076_, _077_, _078_
, _079_, _080_, _081_, _082_, _083_, _084_, _085_, _086_, _087_, _088_, _089_, _090_, _091_, _092_, _093_, _094_, _095_, _096_, _097_, _098_, _099_
, _100_, _101_, _102_, _103_, _104_, _105_, _106_, _107_, _108_, _109_, _110_, _111_, _112_, _113_, _114_, _115_, _116_, _117_, _118_, _119_, _120_
, _121_, _122_, _123_, _124_, _125_, _126_, _127_, _128_, _129_, _130_, _131_, _132_, _133_, _134_, _135_, _136_, _137_, _138_, _139_, _140_, _141_
, _142_, _143_, _144_);
  input _037_;
  wire _037_;
  input _038_;
  wire _038_;
  input _039_;
  wire _039_;
  input _040_;
  wire _040_;
  input _041_;
  wire _041_;
  input _042_;
  wire _042_;
  input _043_;
  wire _043_;
  input _044_;
  wire _044_;
  input _045_;
  wire _045_;
  input _046_;
  wire _046_;
  input _047_;
  wire _047_;
  input _048_;
  wire _048_;
  input _049_;
  wire _049_;
  input _050_;
  wire _050_;
  input _051_;
  wire _051_;
  input _052_;
  wire _052_;
  input _053_;
  wire _053_;
  input _054_;
  wire _054_;
  input _055_;
  wire _055_;
  input _056_;
  wire _056_;
  input _057_;
  wire _057_;
  input _058_;
  wire _058_;
  input _059_;
  wire _059_;
  input _060_;
  wire _060_;
  input _061_;
  wire _061_;
  input _062_;
  wire _062_;
  input _063_;
  wire _063_;
  input _064_;
  wire _064_;
  output _065_;
  wire _065_;
  output _066_;
  wire _066_;
  output _067_;
  wire _067_;
  output _068_;
  wire _068_;
  output _069_;
  wire _069_;
  output _070_;
  wire _070_;
  output _071_;
  wire _071_;
  output _072_;
  wire _072_;
  output _073_;
  wire _073_;
  output _074_;
  wire _074_;
  output _075_;
  wire _075_;
  output _076_;
  wire _076_;
  output _077_;
  wire _077_;
  output _078_;
  wire _078_;
  output _079_;
  wire _079_;
  output _080_;
  wire _080_;
  output _081_;
  wire _081_;
  output _082_;
  wire _082_;
  output _083_;
  wire _083_;
  output _084_;
  wire _084_;
  output _085_;
  wire _085_;
  output _086_;
  wire _086_;
  output _087_;
  wire _087_;
  output _088_;
  wire _088_;
  output _089_;
  wire _089_;
  output _090_;
  wire _090_;
  output _091_;
  wire _091_;
  output _092_;
  wire _092_;
  output _093_;
  wire _093_;
  output _094_;
  wire _094_;
  output _095_;
  wire _095_;
  output _096_;
  wire _096_;
  output _097_;
  wire _097_;
  output _098_;
  wire _098_;
  output _099_;
  wire _099_;
  output _100_;
  wire _100_;
  output _101_;
  wire _101_;
  output _102_;
  wire _102_;
  output _103_;
  wire _103_;
  output _104_;
  wire _104_;
  output _105_;
  wire _105_;
  output _106_;
  wire _106_;
  output _107_;
  wire _107_;
  output _108_;
  wire _108_;
  output _109_;
  wire _109_;
  output _110_;
  wire _110_;
  output _111_;
  wire _111_;
  output _112_;
  wire _112_;
  output _113_;
  wire _113_;
  output _114_;
  wire _114_;
  output _115_;
  wire _115_;
  output _116_;
  wire _116_;
  output _117_;
  wire _117_;
  output _118_;
  wire _118_;
  output _119_;
  wire _119_;
  output _120_;
  wire _120_;
  output _121_;
  wire _121_;
  output _122_;
  wire _122_;
  output _123_;
  wire _123_;
  output _124_;
  wire _124_;
  output _125_;
  wire _125_;
  output _126_;
  wire _126_;
  output _127_;
  wire _127_;
  output _128_;
  wire _128_;
  output _129_;
  wire _129_;
  output _130_;
  wire _130_;
  output _131_;
  wire _131_;
  output _132_;
  wire _132_;
  output _133_;
  wire _133_;
  output _134_;
  wire _134_;
  output _135_;
  wire _135_;
  output _136_;
  wire _136_;
  output _137_;
  wire _137_;
  output _138_;
  wire _138_;
  output _139_;
  wire _139_;
  output _140_;
  wire _140_;
  output _141_;
  wire _141_;
  output _142_;
  wire _142_;
  output _143_;
  wire _143_;
  output _144_;
  wire _144_;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(_052_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(_051_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xor2_1 _147_ (
    .A(_052_),
    .B(_054_),
    .X(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(_005_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _149_ (
    .A(_062_),
    .B(_056_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _150_ (
    .A(_053_),
    .B(_064_),
    .X(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _151_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xor2_1 _152_ (
    .A(_057_),
    .B(_060_),
    .X(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(_061_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _155_ (
    .A(_059_),
    .B(_055_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(_058_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _157_ (
    .A(_005_),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _158_ (
    .A(_011_),
    .B(_014_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xor2_1 _159_ (
    .A(_057_),
    .B(_063_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _160_ (
    .A(_056_),
    .B(_054_),
    .X(_016_)
  );
  sky130_fd_sc_hd__xnor3_1 _161_ (
    .A(_056_),
    .B(_058_),
    .C(_054_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _162_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(_053_),
    .B(_055_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _164_ (
    .A(_059_),
    .B(_060_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _165_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(_061_),
    .B(_022_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor3_1 _168_ (
    .A(_061_),
    .B(_018_),
    .C(_021_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_062_),
    .B(_023_),
    .X(_141_)
  );
  sky130_fd_sc_hd__xnor2_1 _170_ (
    .A(_052_),
    .B(_051_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _171_ (
    .A(_023_),
    .B(_072_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(_062_),
    .B(_024_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__xor2_1 _173_ (
    .A(_062_),
    .B(_024_),
    .X(_138_)
  );
  sky130_fd_sc_hd__xnor2_1 _174_ (
    .A(_054_),
    .B(_057_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _175_ (
    .A(_054_),
    .B(_009_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _176_ (
    .A(_006_),
    .B(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _177_ (
    .A(_071_),
    .B(_019_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xnor3_1 _178_ (
    .A(_071_),
    .B(_058_),
    .C(_019_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _179_ (
    .A(_059_),
    .B(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_061_),
    .B(_031_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__xor2_1 _182_ (
    .A(_061_),
    .B(_031_),
    .X(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _183_ (
    .A(_059_),
    .B(_061_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _184_ (
    .A(_019_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(_057_),
    .B(_017_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _186_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _187_ (
    .A(_035_),
    .SLEEP(_060_),
    .X(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(_060_),
    .B(_035_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _189_ (
    .A(_072_),
    .B(_035_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xnor2_1 _190_ (
    .A(_060_),
    .B(_128_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _191_ (
    .A(_009_),
    .B(_016_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _192_ (
    .A(_030_),
    .B(_036_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xor2_1 _193_ (
    .A(_029_),
    .B(_036_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _194_ (
    .A(_056_),
    .B(_053_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _195_ (
    .A(_025_),
    .B(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _196_ (
    .A(_012_),
    .B(_001_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(_013_),
    .B(_001_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(_072_),
    .B(_117_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__xnor2_1 _199_ (
    .A(_072_),
    .B(_119_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__xor2_1 _200_ (
    .A(_017_),
    .B(_028_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(_057_),
    .B(_108_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _202_ (
    .A(_019_),
    .B(_025_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xor2_1 _203_ (
    .A(_055_),
    .B(_001_),
    .X(_105_)
  );
  sky130_fd_sc_hd__xor2_1 _204_ (
    .A(_019_),
    .B(_072_),
    .X(_092_)
  );
  sky130_fd_sc_hd__xor2_1 _205_ (
    .A(_072_),
    .B(_107_),
    .X(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(_056_),
    .B(_002_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xor2_1 _207_ (
    .A(_056_),
    .B(_002_),
    .X(_102_)
  );
  sky130_fd_sc_hd__xnor2_1 _208_ (
    .A(_053_),
    .B(_084_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _209_ (
    .A(_005_),
    .B(_000_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(_055_),
    .B(_003_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xor2_1 _211_ (
    .A(_055_),
    .B(_003_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(_054_),
    .B(_019_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xor2_1 _213_ (
    .A(_054_),
    .B(_019_),
    .X(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _214_ (
    .A(_072_),
    .B(_093_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xor2_1 _215_ (
    .A(_051_),
    .B(_053_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _216_ (
    .A(_052_),
    .B(_004_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _217_ (
    .A(_071_),
    .B(_004_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _218_ (
    .A(_063_),
    .B(_144_),
    .Y(_142_)
  );
  assign _125_ = _120_;
  assign _124_ = _062_;
  assign _123_ = 1'b1;
  assign _122_ = _061_;
  assign _121_ = 1'b1;
  assign _115_ = _108_;
  assign _113_ = _108_;
  assign _112_ = _060_;
  assign _111_ = 1'b1;
  assign _110_ = _059_;
  assign _109_ = 1'b1;
  assign _103_ = _096_;
  assign _101_ = _096_;
  assign _100_ = _058_;
  assign _099_ = 1'b1;
  assign _098_ = _057_;
  assign _097_ = 1'b1;
  assign _091_ = _084_;
  assign _089_ = _084_;
  assign _088_ = _056_;
  assign _087_ = 1'b1;
  assign _086_ = _055_;
  assign _085_ = 1'b1;
  assign _083_ = _053_;
  assign _081_ = _053_;
  assign _079_ = _052_;
  assign _077_ = _052_;
  assign _076_ = _054_;
  assign _075_ = 1'b1;
  assign _074_ = _053_;
  assign _073_ = 1'b1;
  assign _069_ = 1'b1;
  assign _068_ = _052_;
  assign _067_ = 1'b1;
  assign _066_ = _051_;
  assign _065_ = 1'b1;
  assign _139_ = _132_;
  assign _137_ = _132_;
  assign _136_ = _064_;
  assign _135_ = 1'b1;
  assign _134_ = _063_;
  assign _133_ = 1'b1;
  assign _127_ = _120_;
endmodule
